credentials:
  usernames:
    ktriggs:
      email: kieranjamestriggs@gmail.com
      name: Kieran Triggs
      password: 'Password1' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - kieranjamestriggs@gmail.com
